name: "GH Action.py"
description: 'Github actions starter for python script with container.'
author: "lsetiawan <https://github.com/lsetiawan>"
inputs:
  seconds:  # id of input
    description: 'Number of seconds to  wait'
    required: true
    default: "10"
outputs:
  time: # id of output
    description: 'The time the script finished.'
runs:
  using: 'docker'
  image: 'Dockerfile'

run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Updated Static Content"
         git push
